##[>] 🤖🤖
require_relative 'repo_writer'
require_relative 'aggregate'

module Automation
  # CiVarsWriter generates ci-variables' tfvars from the graph: one unit per consumer, one for producers.
  module CiVarsWriter
    REPO = 'cross-repo/infra/ci-variables'
    HEADER = '# generated by cross-repo/automation, do not edit'.freeze
    GROUP = 'konradodwrot'

    # Renders every consumer's tfvars plus the producers' file, keyed by repo-relative path.
    #[why] released carries the version the triggering release just minted: a producer's
    #   artifacts-produced.yml renders its version from the group variable, which still names the
    #   version published *before* this release, so regenerating from declarations alone propagates
    #   a stale pin and the release never reaches its consumers
    PRODUCERS_FILE = 'live/producers/generated.auto.tfvars'.freeze

    def self.files(repos, released = {}, current = {}, current_consumers = {})
      artifacts = Aggregate.artifacts(repos)
      consumers = repos.sort.to_h { |repo, r| [repo, consumer_vars(r, artifacts, current_consumers[repo] || {})] }
                       .reject { |_, v| v.empty? }
      consumers.to_h { |repo, vars| [consumer_path(repo), consumer_file(repo, vars)] }
               .merge(PRODUCERS_FILE => producer_file(repos, artifacts, released, current))
    end

    def self.consumer_path(repo)
      "live/consumers/#{repo}/generated.auto.tfvars"
    end

    # A consumer's variables: its version for every artifact it consumes, never below the pin the
    # file already holds.
    #[why] a consumer's declaration lags every hand pin: regenerating from it alone dragged ten
    #   consumers back to a months-old image at the next release
    def self.consumer_vars(declaration, artifacts, current = {})
      (declaration['upstream'] || []).filter_map do |entry|
        key = artifacts.dig(entry['uri'], 'versionEnvVar')
        [key, highest(entry['version'], current[key])] if key && entry['version']
      end.sort.to_h
    end

    def self.consumer_file(repo, vars)
      render_tfvars("project = #{"#{GROUP}/#{repo}".inspect}", vars)
    end

    # One aligned assignment per variable, the shape ci-variables' modules declare as inputs.
    def self.render_tfvars(scope, vars)
      width = vars.keys.map(&:length).max || 0
      body = [HEADER, scope, '', *vars.map { |key, version| "#{key.ljust(width)} = #{version.inspect}" }]
      "#{body.join("\n")}\n"
    end

    # The producers' file: each artifact's highest known version, the release that triggered this run winning.
    def self.producer_file(repos, artifacts, released = {}, current = {})
      vars = repos.sort.flat_map { |_repo, r| r['downstream'] || [] }.filter_map do |entry|
        key = artifacts.dig(entry['uri'], 'versionEnvVar')
        next unless key

        version = released[entry['uri']] || highest(entry['version'], current[key])
        [key, version] if version
      end.sort.to_h
      render_tfvars("group = #{GROUP.inspect}", vars)
    end

    def self.highest(*versions)
      versions.compact.max_by { |v| semver_key(v) }
    end

    # The last vX.Y.Z in a version string as a sortable triple; an unparsable version sorts lowest.
    def self.semver_key(version)
      m = version.to_s.scan(/v(\d+)\.(\d+)\.(\d+)/).last
      m ? m.map(&:to_i) : [-1]
    end

    # The producer pins the file currently holds, {key => version}.
    def self.parse_tfvars(body)
      body.to_s.scan(/^(\w+)\s*=\s*"([^"]*)"$/).to_h
    end

    def self.write(repos, moved:, released: {}, group: GROUP, writer: nil, dry_run: false)
      writer ||= RepoWriter.new(repo: REPO, group: group, dry_run: dry_run)
      current = parse_tfvars(writer.read(PRODUCERS_FILE))
      current_consumers = repos.keys.to_h { |repo| [repo, parse_tfvars(writer.read(consumer_path(repo)))] }
      writer.write(files(repos, released, current, current_consumers), message: "[vars] #{moved}")
    end
  end
end
##[<] 🤖🤖
