##[>] 🤖🤖
require_relative 'repo_writer'
require_relative 'aggregate'

module Automation
  # CiVarsWriter generates ci-variables' tfvars from the graph: one unit per consumer, one for producers.
  module CiVarsWriter
    REPO = 'cross-repo/infra/ci-variables'
    HEADER = '# generated by cross-repo/automation, do not edit'.freeze
    GROUP = 'konradodwrot'

    # Renders every consumer's tfvars plus the producers' file, keyed by repo-relative path.
    def self.files(repos)
      artifacts = Aggregate.artifacts(repos)
      consumers = repos.sort.to_h { |repo, r| [repo, consumer_vars(r, artifacts)] }.reject { |_, v| v.empty? }
      consumers.to_h { |repo, vars| ["live/consumers/#{repo}/generated.auto.tfvars", consumer_file(repo, vars)] }
               .merge('live/producers/generated.auto.tfvars' => producer_file(repos, artifacts))
    end

    # A consumer's variables: its version for every artifact it consumes.
    def self.consumer_vars(declaration, artifacts)
      (declaration['consumes'] || []).filter_map do |entry|
        key = artifacts.dig(entry['uri'], 'versionEnvVar')
        [key, entry['version']] if key && entry['version']
      end.sort.to_h
    end

    def self.consumer_file(repo, vars)
      render_tfvars("project = #{"#{GROUP}/#{repo}".inspect}", vars)
    end

    # One aligned assignment per variable, the shape ci-variables' modules declare as inputs.
    def self.render_tfvars(scope, vars)
      width = vars.keys.map(&:length).max || 0
      body = [HEADER, scope, '', *vars.map { |key, version| "#{key.ljust(width)} = #{version.inspect}" }]
      "#{body.join("\n")}\n"
    end

    # The producers' file: each artifact's latest, determined by the repo that publishes it.
    def self.producer_file(repos, artifacts)
      vars = repos.sort.flat_map { |_repo, r| r['produces'] || [] }.filter_map do |entry|
        key = artifacts.dig(entry['uri'], 'versionEnvVar')
        [key, entry['version']] if key && entry['version']
      end.sort.to_h
      render_tfvars("group = #{GROUP.inspect}", vars)
    end

    def self.write(repos, moved:, group: GROUP, writer: nil, dry_run: false)
      writer ||= RepoWriter.new(repo: REPO, group: group, dry_run: dry_run)
      writer.write(files(repos), message: "[vars] #{moved}")
    end
  end
end
##[<] 🤖🤖
